development:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: <%= ENV["DATABASE_NAME"] || "vua-than_development" %>
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  database: <%= ENV["DATABASE_NAME"] || "vua-than_test" %>
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 15 %>
  database: <%= ENV["DATABASE_NAME"] || "vua-than_production" %>
